# Generated by Django 5.0.2 on 2024-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menu_menuid_alter_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(default='2024-09-21'),
        ),
    ]
