# Generated by Django 5.0.2 on 2024-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
