# Generated by Django 5.0.2 on 2024-09-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(default='2024-09-24'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('Reservation_date', 'Reservation_slot')},
        ),
    ]
