# Generated by Django 5.0.2 on 2024-09-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_first_name_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='MenuID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
